package com.dy.colony.greendao.daos;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dy.colony.greendao.beans.Company_Point;
import com.dy.colony.greendao.beans.Company_Point_Unit;
import com.dy.colony.greendao.beans.Detection_Record_FGGD_NC;
import com.dy.colony.greendao.beans.FGGDTestItem;
import com.dy.colony.greendao.beans.FoodItemAndStandard;
import com.dy.colony.greendao.beans.JTJPoint;
import com.dy.colony.greendao.beans.JTJTestItem;
import com.dy.colony.greendao.beans.Simple33;
import com.dy.colony.greendao.beans.User;

import com.dy.colony.greendao.daos.Company_PointDao;
import com.dy.colony.greendao.daos.Company_Point_UnitDao;
import com.dy.colony.greendao.daos.Detection_Record_FGGD_NCDao;
import com.dy.colony.greendao.daos.FGGDTestItemDao;
import com.dy.colony.greendao.daos.FoodItemAndStandardDao;
import com.dy.colony.greendao.daos.JTJPointDao;
import com.dy.colony.greendao.daos.JTJTestItemDao;
import com.dy.colony.greendao.daos.Simple33Dao;
import com.dy.colony.greendao.daos.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig company_PointDaoConfig;
    private final DaoConfig company_Point_UnitDaoConfig;
    private final DaoConfig detection_Record_FGGD_NCDaoConfig;
    private final DaoConfig fGGDTestItemDaoConfig;
    private final DaoConfig foodItemAndStandardDaoConfig;
    private final DaoConfig jTJPointDaoConfig;
    private final DaoConfig jTJTestItemDaoConfig;
    private final DaoConfig simple33DaoConfig;
    private final DaoConfig userDaoConfig;

    private final Company_PointDao company_PointDao;
    private final Company_Point_UnitDao company_Point_UnitDao;
    private final Detection_Record_FGGD_NCDao detection_Record_FGGD_NCDao;
    private final FGGDTestItemDao fGGDTestItemDao;
    private final FoodItemAndStandardDao foodItemAndStandardDao;
    private final JTJPointDao jTJPointDao;
    private final JTJTestItemDao jTJTestItemDao;
    private final Simple33Dao simple33Dao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        company_PointDaoConfig = daoConfigMap.get(Company_PointDao.class).clone();
        company_PointDaoConfig.initIdentityScope(type);

        company_Point_UnitDaoConfig = daoConfigMap.get(Company_Point_UnitDao.class).clone();
        company_Point_UnitDaoConfig.initIdentityScope(type);

        detection_Record_FGGD_NCDaoConfig = daoConfigMap.get(Detection_Record_FGGD_NCDao.class).clone();
        detection_Record_FGGD_NCDaoConfig.initIdentityScope(type);

        fGGDTestItemDaoConfig = daoConfigMap.get(FGGDTestItemDao.class).clone();
        fGGDTestItemDaoConfig.initIdentityScope(type);

        foodItemAndStandardDaoConfig = daoConfigMap.get(FoodItemAndStandardDao.class).clone();
        foodItemAndStandardDaoConfig.initIdentityScope(type);

        jTJPointDaoConfig = daoConfigMap.get(JTJPointDao.class).clone();
        jTJPointDaoConfig.initIdentityScope(type);

        jTJTestItemDaoConfig = daoConfigMap.get(JTJTestItemDao.class).clone();
        jTJTestItemDaoConfig.initIdentityScope(type);

        simple33DaoConfig = daoConfigMap.get(Simple33Dao.class).clone();
        simple33DaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        company_PointDao = new Company_PointDao(company_PointDaoConfig, this);
        company_Point_UnitDao = new Company_Point_UnitDao(company_Point_UnitDaoConfig, this);
        detection_Record_FGGD_NCDao = new Detection_Record_FGGD_NCDao(detection_Record_FGGD_NCDaoConfig, this);
        fGGDTestItemDao = new FGGDTestItemDao(fGGDTestItemDaoConfig, this);
        foodItemAndStandardDao = new FoodItemAndStandardDao(foodItemAndStandardDaoConfig, this);
        jTJPointDao = new JTJPointDao(jTJPointDaoConfig, this);
        jTJTestItemDao = new JTJTestItemDao(jTJTestItemDaoConfig, this);
        simple33Dao = new Simple33Dao(simple33DaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Company_Point.class, company_PointDao);
        registerDao(Company_Point_Unit.class, company_Point_UnitDao);
        registerDao(Detection_Record_FGGD_NC.class, detection_Record_FGGD_NCDao);
        registerDao(FGGDTestItem.class, fGGDTestItemDao);
        registerDao(FoodItemAndStandard.class, foodItemAndStandardDao);
        registerDao(JTJPoint.class, jTJPointDao);
        registerDao(JTJTestItem.class, jTJTestItemDao);
        registerDao(Simple33.class, simple33Dao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        company_PointDaoConfig.clearIdentityScope();
        company_Point_UnitDaoConfig.clearIdentityScope();
        detection_Record_FGGD_NCDaoConfig.clearIdentityScope();
        fGGDTestItemDaoConfig.clearIdentityScope();
        foodItemAndStandardDaoConfig.clearIdentityScope();
        jTJPointDaoConfig.clearIdentityScope();
        jTJTestItemDaoConfig.clearIdentityScope();
        simple33DaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public Company_PointDao getCompany_PointDao() {
        return company_PointDao;
    }

    public Company_Point_UnitDao getCompany_Point_UnitDao() {
        return company_Point_UnitDao;
    }

    public Detection_Record_FGGD_NCDao getDetection_Record_FGGD_NCDao() {
        return detection_Record_FGGD_NCDao;
    }

    public FGGDTestItemDao getFGGDTestItemDao() {
        return fGGDTestItemDao;
    }

    public FoodItemAndStandardDao getFoodItemAndStandardDao() {
        return foodItemAndStandardDao;
    }

    public JTJPointDao getJTJPointDao() {
        return jTJPointDao;
    }

    public JTJTestItemDao getJTJTestItemDao() {
        return jTJTestItemDao;
    }

    public Simple33Dao getSimple33Dao() {
        return simple33Dao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
